# Generated by Django 5.1.6 on 2025-04-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
