# Generated by Django 5.1.6 on 2025-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0003_list_alter_task_section_section_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='List',
            new_name='list',
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
